### ISSUE TITLE
Pypi beatcop

### ISSUE THREAD

**Issue by oppianmatt** [Luluvise/BeatCop#2]
It would be nice to have this in pypi so we can install it from requirements.

**Comment by josefdlange** [comment]
+1

I agree with this. Also, changing perhaps the means of execution to allow both custom runners (ones that invoke the BeatCop class on their own) and a CLI, much like Celery does. I have my configuration set up the way I like it, a lot of which is based on dynamic values from the environment and from external services and sources, and as such it's difficult if not impossible to replicate that into the .ini file again and again.

I'm experimenting with my own fork of the project and if I come up with anything useful, I'll definitely send a pull request.

@ingmar, what say you?

**Comment by HoverHell** [comment]
Did that (also had to add manifest for it to work): https://pypi.python.org/pypi/BeatCop

**Comment by ingmar** [comment]
@HoverHell Nice one. Minor niggle, the Markdown links aren't rendering well on PyPi.

Happy to merge a PR if you can be bothered.

**Comment by HoverHell** [comment]
> Minor niggle, the Markdown links aren't rendering well on PyPi.

No good solution to that; either requiring another module in setup.py just for the pypi description, or changing from md to rst.

**Comment by HoverHell** [comment]
> No good solution to that;

... did a non-good-solution of editing the rst in through the webinterface.
